// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZKs4DQkiJlxYXxfbg5HUSFRLMe8QRJM',
    appId: '1:949628711442:android:38812fa671b8ed16625ecb',
    messagingSenderId: '949628711442',
    projectId: 'edini-32lak',
    storageBucket: 'edini-32lak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxGbK2kijXxmv28AbDXfdu9loU-6TT8Ys',
    appId: '1:949628711442:ios:c24c7e1863e5f7b3625ecb',
    messagingSenderId: '949628711442',
    projectId: 'edini-32lak',
    storageBucket: 'edini-32lak.appspot.com',
    androidClientId: '949628711442-k03arvv3jf8v8f6p15ba3gvn964kp1bh.apps.googleusercontent.com',
    iosClientId: '949628711442-5mjomkcgmqsq0onqb0dq8f1ufsfh6veg.apps.googleusercontent.com',
    iosBundleId: 'com.getmind.quizapp',
  );
}
